# Generated by Django 4.1.3 on 2022-11-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BanSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_source', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_agent', models.CharField(max_length=1024)),
                ('client_name', models.CharField(max_length=96)),
                ('fav_entry_id', models.BigIntegerField()),
                ('fav_title_id', models.BigIntegerField()),
                ('fav_title_name', models.CharField(max_length=128)),
                ('fav_author_id', models.BigIntegerField()),
                ('fav_author_name', models.CharField(max_length=96)),
                ('author_name_list', models.CharField(max_length=100000)),
                ('author_id_list', models.CharField(max_length=100000)),
                ('author_list_size', models.IntegerField()),
                ('total_action', models.IntegerField()),
                ('successful_action', models.IntegerField()),
                ('is_early_stopped', models.IntegerField()),
                ('log', models.CharField(max_length=1000000)),
                ('ban_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_data_collector.banmode')),
                ('ban_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_data_collector.bansource')),
                ('log_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_data_collector.loglevel')),
            ],
        ),
    ]
