# Generated by Django 4.1.3 on 2023-03-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_agent', models.CharField(max_length=1024)),
                ('client_name', models.CharField(max_length=96)),
                ('client_uid', models.BigIntegerField()),
                ('click_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_data_collector.clicktype')),
            ],
        ),
    ]
