# Generated by Django 4.1.3 on 2023-03-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_collector', '0002_clicktype_clientanalytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientAnalytics',
            new_name='ClientAnalytic',
        ),
    ]
