# Generated by Django 4.1.3 on 2023-06-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_collector', '0003_rename_clientanalytics_clientanalytic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_source', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eksi_sozluk_url', models.CharField(max_length=100)),
                ('send_data', models.BooleanField()),
                ('send_client_name', models.BooleanField()),
                ('enable_noob_ban', models.BooleanField()),
                ('enable_mute', models.BooleanField()),
                ('enable_title_ban', models.BooleanField()),
                ('enable_anaylsis_before_operations', models.BooleanField()),
                ('enable_only_required_actions', models.BooleanField()),
                ('enable_protect_followed_users', models.BooleanField()),
                ('ban_premium_icons', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='clientdata',
            name='version',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='click_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client_data_collector.clicksource'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='target_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client_data_collector.targettype'),
        ),
    ]
