# Generated by Django 4.1.3 on 2023-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_collector', '0004_clicksource_config_targettype_clientdata_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='fav_author_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='fav_entry_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='fav_title_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
