# Generated by Django 4.1.3 on 2023-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionconfig',
            name='eksi_sozluk_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
