# Generated by Django 4.1.3 on 2023-09-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_actionconfig_eksi_sozluk_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionconfig',
            name='send_client_name',
        ),
    ]
