# Generated by Django 4.1.3 on 2023-09-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_actionconfig_send_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='total_action',
            new_name='performed_action',
        ),
        migrations.AddField(
            model_name='action',
            name='planned_action',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
