# Generated by Django 4.1.3 on 2024-03-02 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_total_action_action_performed_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpecifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_specifier', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='time_specifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.timespecifier'),
        ),
    ]
