# Generated by Django 5.2.17 on 2026-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timespecifier_action_time_specifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='job_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='job_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='config_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
