# Generated by Django 4.1.3 on 2026-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timespecifier_action_time_specifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='bulk_action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='date_criteria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='source_list',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
